### ISSUE TITLE
Need replacement of styleguide to use vscode linter extensions

### ISSUE THREAD

**Issue by vairamsvsjdo** [wpilibsuite/styleguide#158]

**Comment by calcmogul** [comment]
What do you mean by replacement? Are you talking about the styleguide repo or wpiformat? Could elaborate on the problem you're having? (What you were trying to do, what should have happened, what you saw instead, etc.)

**Comment by vairamsvsjdo** [comment]
@calcmogul 
I was looking to see if the need to install additional software of python and styleguid be replaced with another gradle plugin and/or vscode extension.

Use the styleguide as documented. Works perfect!!
