### ISSUE TITLE
Reenable macOS CI

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/styleguide#240]
We had to disable it because brew dropped `clang-format@14`, the version of clang-format we've standardized on. Perhaps `llvm@14` contains clang-format?

**Comment by auscompgeek** [comment]
```console
> /usr/local/opt/llvm@14/bin/clang-format --version
Homebrew clang-format version 14.0.6
```

Should be easy enough to use in CI by [appending it to the `PATH`](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path).
