### ISSUE TITLE
C++ Method Naming

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/styleguide#46]
Now that we have namespaces, we should change all of our C++ method names to be lower camel case.

@SamCarlberg

**Comment by SamCarlberg** [comment]
Yes please

**Comment by nightpool** [comment]
This would be a large breaking change for little benefit.

**Comment by ThadHouse** [comment]
That doesn't match most normal C++ naming conventions. The standard library is the only thing I know of in C++ that doesn't match that. Otherwise UpperCamelCase is the most common by far.

**Comment by ThadHouse** [comment]
We also are based on only a slightly modified Google Style Guide, which uses PascalCase as a standard. We have used that for years, and shouldn't really change it.
